clang format
git-svn-id: file:///raid/svn-personal/ameba/trunk@8 7c6fbcdb-e420-f942-ac3d-475aac8736fa

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,9 +1,26 @@
 #!/bin/sh
 
+EXPORTS=""
+
 if [ ! -e ./configure.script ]; then
 	echo "configure.script is missing, aborted"
 	exit 1
 fi
+
+for arg in $@; do
+	case "$arg" in
+		--help|-h)
+			echo "$0 configures stuffs for you"
+			echo ""
+			echo "Usage: $0 [options]"
+			exit 0
+			;;
+		*)
+			echo "Invalid option: $arg"
+			exit 1
+			;;
+	esac
+done
 
 echo "$0 is generating config.mk/config.h/Makefile"
 
@@ -196,14 +213,14 @@ cat configure.script | while read a; do
 						if $OPTIONAL; then
 							:
 						else
-							echo "Cannot find a flag for C89!"
+							echo "Cannot find a flag for C89!" > /dev/stderr
 							exit 1
 						fi
 					else
 						echo "$ANSI"
 					fi
 				else
-					echo "Not supported"
+					echo "Not supported" > /dev/stderr
 					exit 1
 				fi
 			fi
@@ -278,14 +295,43 @@ cat configure.script | while read a; do
 						echo "CC=$CC" >> config.mk
 						AFTER 0
 					fi
+					EXPORTS="$EXPORTS CC"
 				else
-					echo "Not supported"
+					echo "Not supported" > /dev/stderr
 					exit 1
 				fi
 			fi
 			;;
-		m)
-			echo "$ARG"
+		m*)
+			PARSE
+			if $RUNIF; then
+				echo "$ARG"
+			fi
+			AFTER 0
+			;;
+		o*)
+			PARSE
+			if $RUNIF; then
+				echo "Creating $ARG"
+				if [ -f $ARG.in ]; then
+					cp $ARG.in /tmp/$ARG.$$.1
+					for i in $EXPORTS; do
+						eval "data=\$$i"
+						data="`echo "$data" | sed -E "s/%/\\\\\%/g"`"
+						sed "s%@$i@%$data%g" /tmp/$ARG.$$.1 > /tmp/$ARG.$$.2
+						mv /tmp/$ARG.$$.2 /tmp/$ARG.$$.1
+					done
+					mv $ARG.$$.1 $ARG
+					AFTER 0
+				else
+					if $OPTIONAL; then
+						AFTER 1
+					else
+						echo "Cannot find $ARG.in!" > /dev/stderr
+						exit 1
+					fi
+				fi
+			fi
 			;;
 	esac
 	DEBUG "--- END Line $a ---"
